/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SaccoService } from "../sacco.service";
import { SaccoCreateInput } from "./SaccoCreateInput";
import { Sacco } from "./Sacco";
import { SaccoFindManyArgs } from "./SaccoFindManyArgs";
import { SaccoWhereUniqueInput } from "./SaccoWhereUniqueInput";
import { SaccoUpdateInput } from "./SaccoUpdateInput";
import { VehicleFindManyArgs } from "../../vehicle/base/VehicleFindManyArgs";
import { Vehicle } from "../../vehicle/base/Vehicle";
import { VehicleWhereUniqueInput } from "../../vehicle/base/VehicleWhereUniqueInput";

export class SaccoControllerBase {
  constructor(protected readonly service: SaccoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sacco })
  async createSacco(@common.Body() data: SaccoCreateInput): Promise<Sacco> {
    return await this.service.createSacco({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Sacco] })
  @ApiNestedQuery(SaccoFindManyArgs)
  async saccos(@common.Req() request: Request): Promise<Sacco[]> {
    const args = plainToClass(SaccoFindManyArgs, request.query);
    return this.service.saccos({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sacco })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sacco(
    @common.Param() params: SaccoWhereUniqueInput
  ): Promise<Sacco | null> {
    const result = await this.service.sacco({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sacco })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSacco(
    @common.Param() params: SaccoWhereUniqueInput,
    @common.Body() data: SaccoUpdateInput
  ): Promise<Sacco | null> {
    try {
      return await this.service.updateSacco({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sacco })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSacco(
    @common.Param() params: SaccoWhereUniqueInput
  ): Promise<Sacco | null> {
    try {
      return await this.service.deleteSacco({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/vehicles")
  @ApiNestedQuery(VehicleFindManyArgs)
  async findVehicles(
    @common.Req() request: Request,
    @common.Param() params: SaccoWhereUniqueInput
  ): Promise<Vehicle[]> {
    const query = plainToClass(VehicleFindManyArgs, request.query);
    const results = await this.service.findVehicles(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        numberPlate: true,

        sacco: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/vehicles")
  async connectVehicles(
    @common.Param() params: SaccoWhereUniqueInput,
    @common.Body() body: VehicleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicles: {
        connect: body,
      },
    };
    await this.service.updateSacco({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/vehicles")
  async updateVehicles(
    @common.Param() params: SaccoWhereUniqueInput,
    @common.Body() body: VehicleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicles: {
        set: body,
      },
    };
    await this.service.updateSacco({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/vehicles")
  async disconnectVehicles(
    @common.Param() params: SaccoWhereUniqueInput,
    @common.Body() body: VehicleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vehicles: {
        disconnect: body,
      },
    };
    await this.service.updateSacco({
      where: params,
      data,
      select: { id: true },
    });
  }
}
